# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 717)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image1 = QtWidgets.QLabel(self.widget)
        self.image1.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.image1.setFont(font)
        self.image1.setObjectName("image1")
        self.verticalLayout.addWidget(self.image1)
        self.img1 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1.sizePolicy().hasHeightForWidth())
        self.img1.setSizePolicy(sizePolicy)
        self.img1.setMinimumSize(QtCore.QSize(0, 0))
        self.img1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.img1.setFrameShape(QtWidgets.QFrame.Box)
        self.img1.setText("")
        self.img1.setScaledContents(True)
        self.img1.setObjectName("img1")
        self.verticalLayout.addWidget(self.img1)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image2 = QtWidgets.QLabel(self.widget)
        self.image2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.image2.setFont(font)
        self.image2.setObjectName("image2")
        self.verticalLayout_3.addWidget(self.image2)
        self.img2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img2.sizePolicy().hasHeightForWidth())
        self.img2.setSizePolicy(sizePolicy)
        self.img2.setFrameShape(QtWidgets.QFrame.Box)
        self.img2.setText("")
        self.img2.setScaledContents(True)
        self.img2.setObjectName("img2")
        self.verticalLayout_3.addWidget(self.img2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.option1 = QtWidgets.QComboBox(self.widget)
        self.option1.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.option1.setFont(font)
        self.option1.setObjectName("option1")
        self.option1.addItem("")
        self.option1.addItem("")
        self.option1.addItem("")
        self.option1.addItem("")
        self.option1.addItem("")
        self.verticalLayout_2.addWidget(self.option1)
        self.edit1 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit1.sizePolicy().hasHeightForWidth())
        self.edit1.setSizePolicy(sizePolicy)
        self.edit1.setMinimumSize(QtCore.QSize(0, 0))
        self.edit1.setFrameShape(QtWidgets.QFrame.Box)
        self.edit1.setText("")
        self.edit1.setScaledContents(True)
        self.edit1.setObjectName("edit1")
        self.verticalLayout_2.addWidget(self.edit1)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.option2 = QtWidgets.QComboBox(self.widget)
        self.option2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.option2.setFont(font)
        self.option2.setObjectName("option2")
        self.option2.addItem("")
        self.option2.addItem("")
        self.option2.addItem("")
        self.option2.addItem("")
        self.option2.addItem("")
        self.verticalLayout_4.addWidget(self.option2)
        self.edit2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit2.sizePolicy().hasHeightForWidth())
        self.edit2.setSizePolicy(sizePolicy)
        self.edit2.setFrameShape(QtWidgets.QFrame.Box)
        self.edit2.setText("")
        self.edit2.setScaledContents(True)
        self.edit2.setObjectName("edit2")
        self.verticalLayout_4.addWidget(self.edit2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mixing = QtWidgets.QLabel(self.widget1)
        self.mixing.setMaximumSize(QtCore.QSize(201, 18))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.mixing.setFont(font)
        self.mixing.setObjectName("mixing")
        self.horizontalLayout.addWidget(self.mixing)
        self.outputoptions = QtWidgets.QComboBox(self.widget1)
        self.outputoptions.setObjectName("outputoptions")
        self.outputoptions.addItem("")
        self.outputoptions.addItem("")
        self.outputoptions.addItem("")
        self.horizontalLayout.addWidget(self.outputoptions)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comp1 = QtWidgets.QLabel(self.widget1)
        self.comp1.setMaximumSize(QtCore.QSize(161, 18))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.comp1.setFont(font)
        self.comp1.setObjectName("comp1")
        self.gridLayout_2.addWidget(self.comp1, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imagechosen1 = QtWidgets.QComboBox(self.widget1)
        self.imagechosen1.setMaximumSize(QtCore.QSize(92, 26))
        self.imagechosen1.setObjectName("imagechosen1")
        self.imagechosen1.addItem("")
        self.imagechosen1.addItem("")
        self.imagechosen1.addItem("")
        self.horizontalLayout_2.addWidget(self.imagechosen1)
        self.ratio1 = QtWidgets.QSlider(self.widget1)
        self.ratio1.setMinimum(0)
        self.ratio1.setMaximum(100)
        self.ratio1.setProperty("value", 0)
        self.ratio1.setOrientation(QtCore.Qt.Horizontal)
        self.ratio1.setObjectName("ratio1")
        self.horizontalLayout_2.addWidget(self.ratio1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.compchosen1 = QtWidgets.QComboBox(self.widget1)
        self.compchosen1.setObjectName("compchosen1")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.verticalLayout_7.addWidget(self.compchosen1)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.output1 = QtWidgets.QLabel(self.widget1)
        self.output1.setMaximumSize(QtCore.QSize(95, 26))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.output1.setFont(font)
        self.output1.setObjectName("output1")
        self.verticalLayout_10.addWidget(self.output1)
        self.imgoutput1 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgoutput1.sizePolicy().hasHeightForWidth())
        self.imgoutput1.setSizePolicy(sizePolicy)
        self.imgoutput1.setFrameShape(QtWidgets.QFrame.Box)
        self.imgoutput1.setText("")
        self.imgoutput1.setScaledContents(True)
        self.imgoutput1.setObjectName("imgoutput1")
        self.verticalLayout_10.addWidget(self.imgoutput1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.output2 = QtWidgets.QLabel(self.widget1)
        self.output2.setMaximumSize(QtCore.QSize(96, 26))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.output2.setFont(font)
        self.output2.setObjectName("output2")
        self.verticalLayout_9.addWidget(self.output2)
        self.imgoutput2 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgoutput2.sizePolicy().hasHeightForWidth())
        self.imgoutput2.setSizePolicy(sizePolicy)
        self.imgoutput2.setFrameShape(QtWidgets.QFrame.Box)
        self.imgoutput2.setText("")
        self.imgoutput2.setScaledContents(True)
        self.imgoutput2.setObjectName("imgoutput2")
        self.verticalLayout_9.addWidget(self.imgoutput2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comp2 = QtWidgets.QLabel(self.widget1)
        self.comp2.setMaximumSize(QtCore.QSize(161, 18))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.comp2.setFont(font)
        self.comp2.setObjectName("comp2")
        self.gridLayout_3.addWidget(self.comp2, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imagechosen2 = QtWidgets.QComboBox(self.widget1)
        self.imagechosen2.setMaximumSize(QtCore.QSize(92, 26))
        self.imagechosen2.setObjectName("imagechosen2")
        self.imagechosen2.addItem("")
        self.imagechosen2.addItem("")
        self.imagechosen2.addItem("")
        self.horizontalLayout_3.addWidget(self.imagechosen2)
        self.ratio2 = QtWidgets.QSlider(self.widget1)
        self.ratio2.setMinimum(0)
        self.ratio2.setMaximum(100)
        self.ratio2.setProperty("value", 0)
        self.ratio2.setOrientation(QtCore.Qt.Horizontal)
        self.ratio2.setObjectName("ratio2")
        self.horizontalLayout_3.addWidget(self.ratio2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.compchosen2 = QtWidgets.QComboBox(self.widget1)
        self.compchosen2.setObjectName("compchosen2")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.verticalLayout_8.addWidget(self.compchosen2)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        self.splitter.raise_()
        self.image2.raise_()
        self.img2.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1141, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image1.setText(_translate("MainWindow", "Image 1"))
        self.image2.setText(_translate("MainWindow", "Image 2"))
        self.option1.setItemText(0, _translate("MainWindow", "Options"))
        self.option1.setItemText(1, _translate("MainWindow", "FT Magnitude"))
        self.option1.setItemText(2, _translate("MainWindow", "FT Phase"))
        self.option1.setItemText(3, _translate("MainWindow", "FT Real component"))
        self.option1.setItemText(4, _translate("MainWindow", "FT Imaginary component"))
        self.option2.setItemText(0, _translate("MainWindow", "Options"))
        self.option2.setItemText(1, _translate("MainWindow", "FT Magnitude"))
        self.option2.setItemText(2, _translate("MainWindow", "FT Phase"))
        self.option2.setItemText(3, _translate("MainWindow", "FT Real component"))
        self.option2.setItemText(4, _translate("MainWindow", "FT Imaginary component"))
        self.mixing.setText(_translate("MainWindow", "Mixer Output To :"))
        self.outputoptions.setItemText(0, _translate("MainWindow", "Options"))
        self.outputoptions.setItemText(1, _translate("MainWindow", "Output 1"))
        self.outputoptions.setItemText(2, _translate("MainWindow", "Output 2"))
        self.comp1.setText(_translate("MainWindow", "Component 1:"))
        self.imagechosen1.setItemText(0, _translate("MainWindow", "Options"))
        self.imagechosen1.setItemText(1, _translate("MainWindow", "Img 1"))
        self.imagechosen1.setItemText(2, _translate("MainWindow", "Img 2"))
        self.compchosen1.setItemText(0, _translate("MainWindow", "Options"))
        self.compchosen1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.compchosen1.setItemText(2, _translate("MainWindow", "Phase"))
        self.compchosen1.setItemText(3, _translate("MainWindow", "Real"))
        self.compchosen1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.compchosen1.setItemText(5, _translate("MainWindow", "uniform magnitude"))
        self.compchosen1.setItemText(6, _translate("MainWindow", "uniform phase "))
        self.output1.setText(_translate("MainWindow", "Output1"))
        self.output2.setText(_translate("MainWindow", "Output2"))
        self.comp2.setText(_translate("MainWindow", "Component 2:"))
        self.imagechosen2.setItemText(0, _translate("MainWindow", "Options"))
        self.imagechosen2.setItemText(1, _translate("MainWindow", "Img 1"))
        self.imagechosen2.setItemText(2, _translate("MainWindow", "Img 2"))
        self.compchosen2.setItemText(0, _translate("MainWindow", "Options"))
        self.compchosen2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.compchosen2.setItemText(2, _translate("MainWindow", "Phase"))
        self.compchosen2.setItemText(3, _translate("MainWindow", "Real"))
        self.compchosen2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.compchosen2.setItemText(5, _translate("MainWindow", "uniform magnitude"))
        self.compchosen2.setItemText(6, _translate("MainWindow", "uniform phase "))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
